ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
  - name: opera
    version: latest
    version: 10
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: android
    version: latest
